spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?useSSL=false
    username: sfg_dev_user
    password: mihai
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      hibernate:
#        hbm2ddl:
#          delimiter: ";"
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: mihai_database_create.sql

